// Chart images are generated by QuickChart.io (a Chart.js-config-to-PNG
// renderer) since the Workers runtime has no native <canvas> support.
// Self-hosters who don't want the external call can run QuickChart's own
// open-source Docker image and point QUICKCHART_BASE_URL at it - the URL
// shape is identical (see discord-bot/README.md).
const DEFAULT_BASE_URL = "https://quickchart.io/chart";

export function buildChartUrl(chartJsConfig: unknown, opts: { baseUrl?: string; width?: number; height?: number } = {}): string {
  const base = opts.baseUrl ?? DEFAULT_BASE_URL;
  const u = new URL(base);
  u.searchParams.set("c", JSON.stringify(chartJsConfig));
  u.searchParams.set("width", String(opts.width ?? 600));
  u.searchParams.set("height", String(opts.height ?? 350));
  u.searchParams.set("backgroundColor", "white");
  return u.toString();
}

export function buildBarChart(labels: string[], values: number[], label: string): string {
  return buildChartUrl({
    type: "bar",
    data: { labels, datasets: [{ label, data: values, backgroundColor: "#3b82f6" }] },
    options: { plugins: { legend: { display: false } } },
  });
}

/** labels x labels grid of numeric intensity, e.g. day-of-week x hour-of-day. */
export function buildHeatmap(xLabels: string[], yLabels: string[], matrix: number[][], title: string): string {
  const max = Math.max(1, ...matrix.flat());
  const points = matrix.flatMap((row, y) => row.map((v, x) => ({ x: xLabels[x], y: yLabels[y], v })));
  const colors = points.map((p) => `rgba(59,130,246,${Math.min(1, p.v / max).toFixed(2)})`);

  return buildChartUrl({
    type: "matrix",
    data: {
      datasets: [
        {
          label: title,
          data: points,
          backgroundColor: colors,
          width: 20,
          height: 20,
        },
      ],
    },
    options: {
      plugins: { legend: { display: false }, title: { display: true, text: title } },
      scales: { x: { type: "category", labels: xLabels }, y: { type: "category", labels: yLabels } },
    },
  });
}
